import { describe, expect, it } from "vitest";
import { normalizeCurrency, summarizeValidation, validateInvoice, type InvoiceInput } from "./validation";
const valid: InvoiceInput = { vendor_name: "Acme", invoice_number: " INV-1 ", invoice_date: "2026-02-28", due_date: "2026-03-30", currency: "aed", subtotal: "100.00", tax_rate: "5", tax_amount: "5.00", total_amount: "105.00", supplier_tax_id: "AE-12345", status: "pending" };
const rules = (input: InvoiceInput) => validateInvoice(input).issues.map((i) => i.ruleId);
describe("expanded invoice validation", () => {
  it("scores a valid invoice transparently", () => { const result = validateInvoice(valid); expect(result.ready).toBe(true); expect(result.overallScore).toBe(100); expect(result.passedRuleCount).toBeGreaterThan(0); expect(result.categoryScores.required_fields).toBe(100); });
  it("reports every required field with detailed correction metadata", () => { const result = validateInvoice({}); expect(result.criticalErrorCount).toBe(6); expect(rules({})).toEqual(expect.arrayContaining(["vendor_name_required", "invoice_number_required", "invoice_date_required", "currency_required", "subtotal_required", "total_amount_required"])); expect(result.issues[0]).toHaveProperty("suggestedCorrection"); });
  it("checks negative, zero, and decimal financial values", () => { expect(rules({ ...valid, subtotal: -1 })).toContain("subtotal_non_negative"); expect(rules({ ...valid, tax_amount: -1 })).toContain("tax_amount_non_negative"); expect(rules({ ...valid, total_amount: 0 })).toContain("total_amount_positive"); expect(rules({ ...valid, subtotal: 0.1, tax_amount: 0.2, total_amount: 0.3, tax_rate: null })).not.toContain("total_equals_subtotal_plus_tax"); });
  it("uses a 0.01 tolerance and validates tax calculations", () => { expect(rules({ ...valid, total_amount: 105.02 })).toContain("total_equals_subtotal_plus_tax"); expect(rules({ ...valid, tax_amount: 6, total_amount: 106 })).toContain("tax_rate_matches_amount"); });
  it("normalizes lowercase and rejects unknown currencies", () => { expect(normalizeCurrency(" aed ")).toBe("AED"); expect(rules({ ...valid, currency: "zzz" })).toContain("currency_unknown"); });
  it("rejects impossible dates and due dates before invoice dates", () => { expect(rules({ ...valid, invoice_date: "2026-02-30" })).toContain("invoice_date_valid"); expect(rules({ ...valid, due_date: "2026-13-01" })).toContain("due_date_valid"); expect(rules({ ...valid, due_date: "2026-01-01" })).toContain("due_date_not_before_invoice_date"); });
  it("reports same-batch and earlier-batch duplicates", () => { const result = validateInvoice(valid, { sameBatch: true, existing: true }); expect(result.issues.map((i) => i.ruleId)).toEqual(expect.arrayContaining(["duplicate_same_batch", "duplicate_existing_invoice"])); });
  it("validates configurable generic tax identifier format", () => { expect(rules({ ...valid, buyer_tax_id: "@" })).toContain("buyer_tax_id_format"); });
});
describe("summaries", () => { it("computes batch statistics and common errors", () => { const summary = summarizeValidation([valid, { ...valid, total_amount: 0 }]); expect(summary.total).toBe(2); expect(summary.ready).toBe(1); expect(summary.notReady).toBe(1); expect(summary.topIssues.length).toBeGreaterThan(0); }); it("handles an empty batch", () => { expect(summarizeValidation([])).toMatchObject({ total: 0, ready: 0, notReady: 0, failed: 0, averageScore: 0 }); }); });
